### ISSUE TITLE
Bold in Word etc.

### ISSUE THREAD

**Issue by tomkeb** [weiweihuanghuang/Work-Sans#1]
It would be nice if the "bold" button in Word, Writer and such programs linked directly to the corresponding weight, as seen e.g. in Adobe Source fonts.

**Comment by weiweihuanghuang** [comment]
Good idea! Will look into this in the future.

**Comment by adrientetar** [comment]
See 3.3.3 Style Linking section of the Glyphs Handbook.

**Comment by tomkeb** [comment]
Resolved in v 1.20!

**Comment by weiweihuanghuang** [comment]
Really? I haven't actually done the style linking yet
