### ISSUE TITLE
ttfautohint on export within Glyphs using Custom Parameters

### ISSUE THREAD

**Issue by davelab6** [weiweihuanghuang/Work-Sans#10]
In https://github.com/weiweihuanghuang/Work-Sans/blob/master/sources/BUILD.txt#L17 you note that a user must run ttfautohint outside of Glyphs, after exporting TTFs. 

However, Glyphs2 has 'custom parameters' on the Font Info, Instances dialog, that allow you to run the bundled copy of ttfautohint within glyphs, on export.

**Comment by weiweihuanghuang** [comment]
Glyphs App doesn't provide a way for ttfautohint to take control files. 

Also I want the TTFs to have their [ROUND_XY_TO_GRID](https://github.com/weiweihuanghuang/Work-Sans/blob/master/sources/BUILD.txt#L45) flags set before hinting with ttfautohint which can't be done in Glyphs App.

**Comment by adrientetar** [comment]
cc @schriftgestalt

**Comment by davelab6** [comment]
@schriftgestalt how does glyphs make TTFs anyway?

**Comment by schriftgestalt** [comment]
Write a stub OTF, remove CFF table and stick in a glyf table in (among a few other things).

**Comment by davelab6** [comment]
How to you build the GLYF table?

**Comment by schriftgestalt** [comment]
> Glyphs App doesn't provide a way for ttfautohint to take control files, which I'm using.
If you need to control individual nodes, it is very tedious to figure out the nodes index. But I’m working on it.

**Comment by schriftgestalt** [comment]
> How to you build the GLYF table?

Build it from scratch.

**Comment by davelab6** [comment]
>> Also I want the TTFs to have their ROUND_XY_TO_GRID flags set before hinting with ttfautohint which can't be done in Glyphs App.
> ...
> [To makes a GLYF table GlyphsApp ] Build it from scratch.

So ROUND_XY_TO_GRID is possible but yet to be implemented?

**Comment by schriftgestalt** [comment]
Couldn't ttfautohint overwrite this?
But I'm planing to change that, I think I changed that already in the dev code.

**Comment by weiweihuanghuang** [comment]
How did things go with this @schriftgestalt

**Comment by schriftgestalt** [comment]
The ROUND_XY_TO_GRID flag should be set now.
