### ISSUE TITLE
NAME table

### ISSUE THREAD

**Issue by davelab6** [weiweihuanghuang/Work-Sans#12]
- [x] Every NAME table ID with a `PlatformID="1"` attribute should be removed.
- [x] In the Bold, the family naming items with `PlatformID="3"`were set incorrectly, and thus the `macStyle` was `0` not `1`. I correct these in https://github.com/google/fonts/commit/0701f6c76da7797af80ac2f26c977fce639b2161 which you can use for comparison :)

**Comment by weiweihuanghuang** [comment]
Re: `In the Bold, the family naming items with PlatformID="3"were set incorrectly, and thus the macStyle was 0 not 1. I correct these in google/fonts@0701f6c which you can use for comparison :)`

Is this to do with style linking? This is something I set through Glyphs App, is this something I should report to Georg?

**Comment by davelab6** [comment]
Yes, I think so. It was weird because the `PID=1` entries were ok

**Comment by weiweihuanghuang** [comment]
Oops, it was my own mistake, I updated the build script to remove the platformID="1" and now there is this difference:

Your version has: 
<fsSelection value="00000000 01000000"/>
Mine:    
<fsSelection value="00000000 00100000"/>

Is that okay?

**Comment by davelab6** [comment]
Those look the same to me?

**Comment by davelab6** [comment]
I think yours is likely better :)

**Comment by davelab6** [comment]
With https://github.com/google/fonts/commit/11cb93b728b3d4de8d1ba6505ead129ebd747e9b then the fonts in google/fonts and your release are 1:1 for the regular family
