### ISSUE TITLE
Hairline modifications for web fonts use

### ISSUE THREAD

**Issue by davelab6** [weiweihuanghuang/Work-Sans#13]
CSSv2/v3 can only handle 9 weights per family, so I think `WorkSans-Hairline.ttf` needs some changes, which I've made at https://github.com/google/fonts/commit/00fefdc3e9045285bf7042947e9e2e5e3877e630

- [x] a usWeightClass of 400 
- [x] rename name table id 6 from `WorkSans-Hairline` to `WorkSansHairline-Regular`
- [x] remove name tables 16 and 17

**Comment by weiweihuanghuang** [comment]
Would it be better to make it the mininum class 100?

**Comment by davelab6** [comment]
CSS can only have weights in 100s, 1-9, but Windows GDI auto-bolds anything with a weight of 249 or less, so the minimum you should use is 250.

**Comment by weiweihuanghuang** [comment]
If its a problem that Windows GDI auto-bolds anything < 250, are the weights at 100, 200 okay for 'Work Sans' family?

**Comment by weiweihuanghuang** [comment]
About to update my repo to match the https://github.com/google/fonts/commit/00fefdc3e9045285bf7042947e9e2e5e3877e630

Only difference is yours:
```
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      1.030;UKWN;WorkSans-Hairline
```
Mine
```
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      1.031;UKWN;WorkSansHairline-Regular
```

**Comment by davelab6** [comment]
> If its a problem that Windows GDI auto-bolds anything < 250, are the weights at 100, 200 okay for 'Work Sans' family?

Ah, no. I suggest flooring the family at 250, eg the Hairline has that value, and incrementing the other very light weights above it. Eg,

```
$ grep usWeightClass *ttx ;
WorkSans-Black.ttx:    <usWeightClass value="900"/>
WorkSans-Bold.ttx:    <usWeightClass value="700"/>
WorkSans-ExtraBold.ttx:    <usWeightClass value="800"/>
WorkSans-ExtraLight.ttx:    <usWeightClass value="200"/> <-- change to 280
WorkSans-Hairline.ttx:    <usWeightClass value="50"/> <-- change to 250
WorkSans-Light.ttx:    <usWeightClass value="300"/>
WorkSans-Medium.ttx:    <usWeightClass value="500"/>
WorkSans-Regular.ttx:    <usWeightClass value="400"/>
WorkSans-SemiBold.ttx:    <usWeightClass value="600"/>
WorkSans-Thin.ttx:    <usWeightClass value="100"/> <-- change to 260
$
```

@twardoch might have a view on this as the same issue came up with the latest versinon of Fira.

> Only difference is yours:

I think the PS Name is a bit arbitrary and your version will work fine; I updated the version to append a g so we can tell its a gf version.

**Comment by tphinney** [comment]
Yes, floor it at 250. Leave the "light" at 300 if you have one, and then space the other weights from 250 up. It sucks, but this is the safest way to ensure nothing bad will happen on Windows in GDI apps.

This issue has been ongoing for at least 15 years now.

Note that it is in fact possible to write Windows GDI apps that won't do this, and only about half of them do. The problem is a combination of GDI behaviors for faux font weights, plus lack of understanding from programmers about the potential for a problem, as the majority of common typefaces would never have this issue—plus, we font developers keep on avoiding the issue on our side.

**Comment by weiweihuanghuang** [comment]
Thanks for the advice, I've implemented the changes
