### ISSUE TITLE
Small issue on the spanish text with special characters

### ISSUE THREAD

**Issue by DoctorMalboro** [weiweihuanghuang/Work-Sans#14]
I've noticed that on the Spanish text the **ñ** didn't appear in **años**. Couldn't figure out if it's a typo or a font issue.

**Comment by weiweihuanghuang** [comment]
What OS and browser are you using?
I'm on Chrome, OS 10:

![screen shot 2015-07-08 at 5 30 10 pm](https://cloud.githubusercontent.com/assets/1271897/8574453/00a523f2-2597-11e5-8535-40c1262fadca.png)

**Comment by DoctorMalboro** [comment]
Firefox 38 on Ubuntu 14.04

![Proof](https://cloud.githubusercontent.com/assets/553651/8574496/4e797e72-256d-11e5-87e7-42a4be33412d.png)

**Comment by weiweihuanghuang** [comment]
Ah! Thanks, I see, it's because the text itself is composed of 

n 
and
 ̃
Which is a combining diacritical mark…
