### ISSUE TITLE
Letter spacing

### ISSUE THREAD

**Issue by JulienJo** [weiweihuanghuang/Work-Sans#19]
Hi! Very nice and cute font. 
By the way, don't you think that the letter-spacing is a bit too large ? 
![letter-spacing](https://cloud.githubusercontent.com/assets/8792500/10785471/ac29f2fa-7d64-11e5-9f0a-e6792b85bfa8.png)
Cheers!

**Comment by weiweihuanghuang** [comment]
I recommend decreasing letterspacing then :) 

I intend Work Sans to be use optimised for running text, it's not going to work perfectly for every size. If I made the entire font tighter it would not look good at the smaller end which is more important for me,
