### ISSUE TITLE
Heavy superscript dots in lightest weights

### ISSUE THREAD

**Issue by michaelrhodes** [weiweihuanghuang/Work-Sans#2]
Hey there, gorgeous work so far. I just had one comment; looking at the specimen, I feel like the superscript dots in the Extra Light (and lighter) are a bit heavier than they should be. What do you think?

**Comment by weiweihuanghuang** [comment]
Thanks for the feedback! I haven't created any superscripted dots, if you're seeing them in a browser or application it's likely it's a faux superscript dot character (scaled to the program or renderers settings).

Unless you mean the tittle on the lowecase i or ė ?

**Comment by michaelrhodes** [comment]
Oh sorry, I was referring to the tittle, dot, and diaeresis.

**Comment by weiweihuanghuang** [comment]
I think you're right Michael! I'll make them a bit smaller

**Comment by michaelrhodes** [comment]
Sorry for the late reply, but yeah, I think you’re right about those comma-based glyphs. :)

**Comment by weiweihuanghuang** [comment]
Fixed!
