### ISSUE TITLE
Can not add letter-spacing on tt characters

### ISSUE THREAD

**Issue by davy-sitompul** [weiweihuanghuang/Work-Sans#20]
Hi, when I type "kevin garett" with letter-spacing 2px the "tt" characters wont get equally spaced. I tried this on photoshop. Thanks.

**Comment by weiweihuanghuang** [comment]
This is because I have a ligature for that combo... good catch! I'll consider a solution. In the meantime you need to disable ligatures for the 'tt'

**Comment by davelab6** [comment]
I think that _IS_ the solution :)

**Comment by davy-sitompul** [comment]
Thanks for the solution and for the great font.
