### ISSUE TITLE
Missing small caps characters in ExtraLight and Light weights

### ISSUE THREAD

**Issue by realjoshharrison** [weiweihuanghuang/Work-Sans#22]
A really lovely font. Thank you for your hard work on this and for making it available.

I've just noticed that the ExtraLight and Light weights are missing X and Y small capitals glyphs.

Thanks again

**Comment by weiweihuanghuang** [comment]
Hey thanks for spotting that! I'll get that fixed soon :)

**Comment by tiagonogueira21** [comment]
@weiweihuanghuang any news on this?

**Comment by weiweihuanghuang** [comment]
Sorry for the late response, fixed!
