### ISSUE TITLE
»How to Generate Web Native Fonts« Link broken

### ISSUE THREAD

**Issue by lnolte** [weiweihuanghuang/Work-Sans#23]
Hi, the link to the Google Font wiki seems to be broken: https://code.google.com/p/googlefontdirectory/wiki/HowToGenerateWebNativeFonts

Does someone know, if they just moved this?

**Comment by weiweihuanghuang** [comment]
@davelab6 what happened to the https://github.com/google/fonts/wiki link? or am I remembering wrong..?

**Comment by lnolte** [comment]
@weiweihuanghuang Thanks :-)
