### ISSUE TITLE
https://weiweihuanghuang.github.io/Work-Sans/worksanswebfonts.css uses unsupported -webkit-font-feature-settings

### ISSUE THREAD

**Issue by litherum** [weiweihuanghuang/Work-Sans#24]
WebKit does not respond to the prefixed "-webkit-font-feature-settings" CSS property. Instead, it responds to the unprefixed "font-feature-settings" CSS property.

Certain selectors (such as .tosf) list the prefixed property but not the unprefixed property.

**Comment by weiweihuanghuang** [comment]
thanks for spotting this, should every selector have both properties?

**Comment by litherum** [comment]
"-webkit-font-feature-settings" is not recognized by any browser at all. All occurrences of it should be replaced with the unprefixed "font-feature-settings"

**Comment by davelab6** [comment]
Finally :D

**Comment by weiweihuanghuang** [comment]
Fixed :D
