### ISSUE TITLE
More arrows

### ISSUE THREAD

**Issue by TuomLarsen** [weiweihuanghuang/Work-Sans#28]
Please, I would be really awesome if you could add these arrows:

http://htmlarrows.com/arrows/left-arrow-with-hook/
http://htmlarrows.com/arrows/right-arrow-with-hook/
http://htmlarrows.com/arrows/anticlockwise-open-circle-arrow/
http://htmlarrows.com/arrows/clockwise-open-circle-arrow/

Thank you very much in advance!

**Comment by weiweihuanghuang** [comment]
Added!

**Comment by TuomLarsen** [comment]
You are the best, thank you!
