### ISSUE TITLE
Italics

### ISSUE THREAD

**Issue by tomkeb** [weiweihuanghuang/Work-Sans#3]
The description says there will be 5 widths… are there also respective italics planned?

**Comment by weiweihuanghuang** [comment]
Yes I'd like to create italics! Italics sooner then the widths I think.

**Comment by PLJNS** [comment]
You've made a beautiful font that I love using, thank you for making it FOSS.

(Italics would be awesome, but I feel so ungrateful pestering you. Just keep making awesome stuff!)

**Comment by jeffmarshall** [comment]
I wonder if we could crowdfund some italics. How much would it cost us, @weiweihuanghuang?

**Comment by skosch** [comment]
I'd be in for sure :+1:

**Comment by weiweihuanghuang** [comment]
Thanks for the support! I'm looking into something now :+1:

**Comment by jeffmarshall** [comment]
Yay! :grinning:

**Comment by raphaelokon** [comment]
Thanks for the great font! :+1:

**Comment by doug-kongregate** [comment]
:+1: for would be happy to support a funding campaign for italics.

**Comment by alfrednerstu** [comment]
Thanks for a beautiful typeface. I would really love to see a regular italic included in the set.

**Comment by jeffmarshall** [comment]
@weiweihuanghuang I made a bountysource: https://www.bountysource.com/issues/9442435-italics

**Comment by jefheaton** [comment]
@weiweihuanghuang Love the typeface also! So many useful bits. I'd contribute to the bounty source for italics, but wanted to make sure that's helpful?

**Comment by brianjoseff** [comment]
@weiweihuanghuang also interested in contributing to bounty! lmk how much you're thinking. would love to support you. beautiful typeface

**Comment by weiweihuanghuang** [comment]
Hi all, thank you so much for your support! I will certainly let you all know about it when plans come up 😊

**Comment by galenwp** [comment]
This is a fantastic typeface.  It'd be especially fantastic to have italics added!

**Comment by voneff** [comment]
@weiweihuanghuang The font is great. Italics would be superfantastic! Any news on this?

**Comment by erickpf** [comment]
Love the typeface as well, and still holding out hope for italics! Is this still a possibility?  If so, when?

**Comment by JolinM** [comment]
<3!!!

**Comment by erickpf** [comment]
Great news @davelab6 !  No pressure, but any sense of timing?

**Comment by davelab6** [comment]
You'd need to ask Wei ;)

**Comment by weiweihuanghuang** [comment]
@erickpf by the end of the year!

**Comment by yannicgraeser** [comment]
Good news :)

**Comment by orffen** [comment]
Looks like commit 02c1b90f534739c3f072c250ab1e2b5dab7b6326 has italics and v2.01 - any chance of a new release or is this still pre-release?

**Comment by davelab6** [comment]
New release coming, pending final review in Google Fonts release process

**Comment by orffen** [comment]
Awesome, thanks!

**Comment by weiweihuanghuang** [comment]
Thanks for the encouragement everyone, Italics is pretty much done, I'm awaiting approval from Google on the final fonts, but you can download the Italics (also has expanded character set and variable font files) from the repo now!

**Comment by williamsetiawan** [comment]
omg so glad to hear that. 

thankyou

**Comment by weiweihuanghuang** [comment]
The Italics is on Google fonts!
https://fonts.google.com/specimen/Work+Sans

**Comment by voneff** [comment]
Congratulations, really great work!
