### ISSUE TITLE
Welsh Characters

### ISSUE THREAD

**Issue by tozerizer** [weiweihuanghuang/Work-Sans#30]
Is it possible to get these characters added to Work-Sans so it can be used in full in the Welsh language?
[](http://welsh.typeit.org/)

Thanks / Diolch!

**Comment by tozerizer** [comment]
http://welsh.typeit.org/

**Comment by weiweihuanghuang** [comment]
Hey sure thing! (Do you need it for webfonts too?)

**Comment by tozerizer** [comment]
Yes please - that would be awesome!Dylan TozerT&T | pr & marketing----------------------------07541 586115----------------------------@tozerizerthetozers.co.uk----------------------------On 6 Aug 2017 22:31, Wei H <notifications@github.com> wrote:Hey sure thing! (Do you need it for webfonts too?)

**Comment by weiweihuanghuang** [comment]
Added!
