### ISSUE TITLE
Using typographical equipment with Google Fonts

### ISSUE THREAD

**Issue by jyng** [weiweihuanghuang/Work-Sans#31]
Hello,
I'm trying to use the arrows, shapes and ornaments via Google Fonts by URL encoding it in the `head`
`<link href="https://fonts.googleapis.com/css?family=Work+Sans&text=%E2%86%90" rel="stylesheet">`

This loads the arrows,however I'm also requesting different weights, so I tried combining it and then Work Sans regular characters breaks but then arrow does not.
`<link href="https://fonts.googleapis.com/css?family=Work+Sans&text=%E2%86%90:100,200,300,400,500,600,700,800,900" rel="stylesheet">`

What is the best approach to use arrows on the web when also requesting multiple weights?

If y'all have any reading material for this, it would be much appreciated. I've found and read these two:
https://stackoverflow.com/questions/18641479/use-a-google-font-and-include-only-a-z-and
https://developers.google.com/fonts/docs/getting_started

**Comment by weiweihuanghuang** [comment]
Thanks for bringing this to attention, unfortunately I don't have any knowledge on how the Google fonts API handles this, hopefully @davelab6 can help?

**Comment by davelab6** [comment]
Please tell the url you tried combining

**Comment by weiweihuanghuang** [comment]
Post got edited and included the original url:

`<link href="https://fonts.googleapis.com/css?family=Work+Sans&text=%E2%86%90:100,200,300,400,500,600,700,800,900" rel="stylesheet">`

**Comment by davelab6** [comment]
The ampersand should be after the 900, easy :)

**Comment by jyng** [comment]
Ah,that worked! 
Phew, I was going down the route that this site was doing: http://www.contemporaryartstavanger.no/ 
by calling fontface with the url directed at github.
`@font-face {
  font-family: 'Worksanslight ';
     url('http://weiweihuanghuang.github.io/Work-Sans/Work-Sans/fonts/webfonts/woff/WorkSans-Light.woff2') format('woff2');
     url('http://weiweihuanghuang.github.io/Work-Sans/Work-Sans/fonts/webfonts/woff/WorkSans-Light.woff') format('woff'),
     url('http://weiweihuanghuang.github.io/Work-Sans/Work-Sans/fonts/webfonts/ttf/WorkSans-Light.ttf') format('truetype');
  font-style: normal;
  font-weight: normal;
}`

Thanks @davelab6!!

**Comment by jyng** [comment]
Oh wait, I got a bit too excited there. I'm running into same issue where the characters don't load but the arrow does. I've attached a screenshot.
My url is now   `<link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900&text=%E2%86%92" rel="stylesheet">`
<img width="1109" alt="screen shot 2017-10-26 at 5 27 08 pm" src="https://user-images.githubusercontent.com/9557907/32082823-11d1eb92-ba73-11e7-8858-1f6cdfab0d5e.png">

**Comment by davelab6** [comment]
Your subset only has the characters you requested, which are just 3,
including that arrow ;)

**Comment by jyng** [comment]
Ah right, if im defining `&text=`  I have to input every character I wish to use after `&text=`. However, this seems a bit verbose if I'm trying to create a type system. Would you know a better method of calling arrows through google fonts?

**Comment by jyng** [comment]
Update: found this workaround.
https://stackoverflow.com/questions/40822458/styled-unicode-arrows-not-showing-up-with-google-fonts-web-font

Looks like Google Font API doesn't include typographical equipment for optimization. Would be nice to make it easily extendable in the future :)

**Comment by davelab6** [comment]
That answer is good; I would have said to encode all 200-300 characters you need, but, indeed, it seems that browsers that support unicode-range will work with 2 `<link>` elements, one with `subset=` and one with `text=`

The arrows are in our expert set (https://github.com/googlefonts/tools/tree/master/encodings/GF%20Glyph%20Sets#gf-latin-expert-271-for-984-total) so I expect them to be included in latin-ext eventually
