### ISSUE TITLE
Adding Vietnamese

### ISSUE THREAD

**Issue by crystaltype** [weiweihuanghuang/Work-Sans#32]
Hi,

I see that this type doesn't have Vietnamese yet.

I'm willing to contribute the complete Vietnamese character set directly, by sending you a 'vietnamese only' glyphapp file for you to review and integrate.

Or, you can make changes and then push your work to master and I will give further feedback :)

Please respond ASAP. Thanks!

P/S: I'm a Vietnamese native speaker and a self-study graphic designer/type designer. I have been working with fonts for over 5 years! I'm here to (hopefully) make google fonts a better place for people using Vietnamese! :) Thanks!

cc': @davelab6

**Comment by weiweihuanghuang** [comment]
Hi @crystaltype that sounds awesome! Would be happy for you to contribute, with some back and forth feedback and revision I'm sure we can get to a really great result!

**Comment by weiweihuanghuang** [comment]
Please send me an email at wweeiihhuuaanngg@gmail.com

**Comment by weiweihuanghuang** [comment]
Thanks for getting the files to me, things look great so far, my feedback:

- I have lowercase, .cap (for uppercase), .asc (for lowercase with ascender) versions of diacritics which are shorter but still in matching weight. The Vietnamese diacritics should also have corrected versions for each diacritic too.
- hookabove: In Medium looks too light at the bottom. In Black master, it's way too light. The terminals also don't conform to the Grotesk sans style of Work Sans, please see the cedilla and ogonek and the way the stroke ending has slight flaring in the end.
- Circumflex: I'd really prefer not to scale these to make Vietnamese diacritics, they should be the same weight and I think the same height (using either the .cap or .asc version of  diacritics), and the second diacritic on top can be smaller and still matching in weight (e.g. the acute, grave, hookabove, tilde):

Current:
![unnamed](https://user-images.githubusercontent.com/1271897/38551790-64b97edc-3cba-11e8-852d-50c2e732efc6.png)

Suggestion:
![unnamed-1](https://user-images.githubusercontent.com/1271897/38551802-6c91cc72-3cba-11e8-8bf8-f79fcdff0b61.png)
What do you think about this? Is this too big? And metrics wise I wonder if that's ok?

**Comment by crystaltype** [comment]
Thank you for your feedback!

> I have lowercase, .cap (for uppercase), .asc (for lowercase with ascender) versions of diacritics which are shorter but still in matching weight. The Vietnamese diacritics should also have corrected versions for each diacritic too

I reviewed and the cap version seems not different from the regular accents. The .asc accents do fit the cap version of Vietnamese really well though. I think I'll be using them for the Vietnamese uppercases.

  

> hookabove: In Medium looks too light at the bottom. In Black master, it's way too light. The terminals also don't conform to the Grotesk sans style of Work Sans, please see the cedilla and ogonek and the way the stroke ending has slight flaring in the end.

It's because of Vietnamese's way of writing the hookabove, it should be lighter in the bottom (for a natural look based on our habit of writing, we tend to loosen the grip towards the end of drawing it). And although it does looks like the vertical flipped cedilla/ogonek , the hookabove actually can't be composed from those two accents. The flaring ending, I think will be considered a mistake of some sort (because we don't extend the tail/bottom of the hookabove while we write). Your suggestion is also good, but the counter of the hookabove is a little small, so in the black/heavy/bold weights it might end up looks like a dot in smaller sizes. 

> Circumflex: I'd really prefer not to scale these to make Vietnamese diacritics, they should be the same weight and I think the same height (using either the .cap or .asc version of  diacritics), and the second diacritic on top can be smaller and still matching in weight (e.g. the acute, grave, hookabove, tilde):

Yes, I think so too at first, but after having a lot of experiences working with large type family, I realized that the black/heavy weights is really problematic if we do it this way. If we keep all the caps accents to have the same weight as the stroke weight, they'll be really hard to make out at smaller sizes (smaller accents but still have bold/heavy weight - for example, the circumflex just looks like a quadrilateral or something like that, or the breve just look like a hyphen). For the most parts, the uppercases with double diacritics rarely used in Vietnamese (excepts for when we're using allcaps), so I think the best way for now is scaling the diacritics (keeping the ratio, not squeezing tho), so it won't look too rough/too big when viewing at large size, it's also can be accepted and doesn't interfere with the flow of reading in the most cases. It also helps with keeping the vertical metrics at a sane amount. 

Although it might not be in sync with the whole font. Vietnamese also only used these accents that some other languages also used: acute, grave, tilde, circumflex and breve. So I think it's not necessary to keep Vietnamese looks good when standing with another language, but we should concentrate on keeping the Vietnamese looks good when standing alone (and also looks good with ONLY those [characters+acute/grave/tilde/circumflex] that other languages are using).

> Actually I realise my previous example looks huge, maybe something like this where the hookabove in circumflex_hookabove is a bit smaller but visually balanced – do you think the flat bottom works? 

It works in some cases, when we draw the hookabove just like we draw the question mark (?). I mean, it will look natural if the hookabove have a bottom stem like the question mark, or else it doesn't look natural at all. If we keep this shape, and with a flat bottom stem, it feels like the bottom stem has been mistakenly erased to me. 

====

I'll use the .asc accents for the uppercases instead tho. Thank you for the suggestions! Please let me know what you think. When all are OK I'll begin to fix and send the file back to you :)
Thanks!

**Comment by weiweihuanghuang** [comment]
Hey @crystaltype, thanks for the response!
The .cap accents are just a tiny bit smaller than the basic accents, and the .asc are even smaller, I think using the .asc makes sense!

>It's because of Vietnamese's way of writing the hookabove, it should be lighter in the bottom (for a natural look based on our habit of writing, we tend to loosen the grip towards the end of drawing it). And although it does looks like the vertical flipped cedilla/ogonek , the hookabove actually can't be composed from those two accents. The flaring ending, I think will be considered a mistake of some sort (because we don't extend the tail/bottom of the hookabove while we write). Your suggestion is also good, but the counter of the hookabove is a little small, so in the black/heavy/bold weights it might end up looks like a dot in smaller sizes.
Thanks for this! Go for what you think looks best then! I'm not concerned about the Black/Heavy weights being used at smaller sizes, the whole typeface will have legibility issues at small sizes. But I do want to keep bold Legible at smaller sizes.

>Yes, I think so too at first, but after having a lot of experiences working with large type family, I realized that the black/heavy weights is really problematic if we do it this way. If we keep all the caps accents to have the same weight as the stroke weight, they'll be really hard to make out at smaller sizes (smaller accents but still have bold/heavy weight - for example, the circumflex just looks like a quadrilateral or something like that, or the breve just look like a hyphen). For the most parts, the uppercases with double diacritics rarely used in Vietnamese (excepts for when we're using allcaps), so I think the best way for now is scaling the diacritics (keeping the ratio, not squeezing tho), so it won't look too rough/too big when viewing at large size, it's also can be accepted and doesn't interfere with the flow of reading in the most cases. It also helps with keeping the vertical metrics at a sane amount.
Sorry I'm a bit confused :) I don't think they should be the stroke weight, I think they shouldn't be just scaled components since then the weight is not correct. I think they should be scaled then adjusted to match in weight with the rest of the accents. Regarding the size of the accents, let's try slightly smaller ones then to compensate.

>It works in some cases, when we draw the hookabove just like we draw the question mark (?). I mean, it will look natural if the hookabove have a bottom stem like the question mark, or else it doesn't look natural at all. If we keep this shape, and with a flat bottom stem, it feels like the bottom stem has been mistakenly erased to me.
So are you saying there's 2 correct ways to draw the hookabove:
1. When the hookabove doesn't end with a vertical down stroke, the bottom of the hookabove should not end horizontally but should end perpendicular to the stroke (like in your first suggestion)?
2. Have a bottom stroke like a question mark?

**Comment by crystaltype** [comment]
> The .cap accents are just a tiny bit smaller than the basic accents, and the .asc are even smaller, I think using the .asc makes sense!
Absolutely!

> Sorry I'm a bit confused :) I don't think they should be the stroke weight, I think they shouldn't be just scaled components since then the weight is not correct. I think they should be scaled then adjusted to match in weight with the rest of the accents. Regarding the size of the accents, let's try slightly smaller ones then to compensate.

Oh, I see, thanks! I'll try your suggestions!

> So are you saying there's 2 correct ways to draw the hookabove:
> 
> When the hookabove doesn't end with a vertical down stroke, the bottom of the hookabove should not end horizontally but should end perpendicular to the stroke (like in your first suggestion)?
> Have a bottom stroke like a question mark?

Yes, that's exactly what I mean. There are some variations but the most correct way should be like that.

**Comment by weiweihuanghuang** [comment]
Hey @crystaltype how's it going :)

**Comment by dasklney** [comment]
Hope we can get the Vietnamese version of this font :D

**Comment by weiweihuanghuang** [comment]
Vietnamese has been added to the latest fonts!
