### ISSUE TITLE
Continuous build

### ISSUE THREAD

**Issue by dany-on-demand** [weiweihuanghuang/Work-Sans#34]
Hi, thanks for the groundbreaking work! Can you set up some sort of a continuous build system so that people who don't run mac can see the master version font?
Or at least convert the .glyphs file to something we can compile on *nix/windows

**Comment by davelab6** [comment]
You could try doing it with fontmake, but, I believe WS uses Glyphsapp
features unsupported in fontmake.

To do with Glyphsapp is maybe possible with applescript & a macOS VM.
Travis offers them.

**Comment by weiweihuanghuang** [comment]
Is this solved now with the full fontmake build?

**Comment by dany-on-demand** [comment]
I suppose, if you keep updating it in tandem, sure!
