### ISSUE TITLE
ij kerning too much?

### ISSUE THREAD

**Issue by davelab6** [weiweihuanghuang/Work-Sans#36]
<img width="165" alt="screen shot 2018-12-02 at 5 32 07 pm" src="https://user-images.githubusercontent.com/261579/49345826-3ade4400-f658-11e8-943a-82e8bd00b9b5.png">

from https://v-fonts.com/

**Comment by weiweihuanghuang** [comment]
@davelab6 what browser and os are you viewing from? Could be this this issue https://github.com/googlei18n/fontmake/issues/481 as this is how it is on my end:
<img width="635" alt="screen shot 2018-12-03 at 12 00 32 pm" src="https://user-images.githubusercontent.com/1271897/49347501-1c795680-f6f3-11e8-924d-5f891662ae1e.png">
