### ISSUE TITLE
Brace layer naming off

### ISSUE THREAD

**Issue by madig** [weiweihuanghuang/Work-Sans#37]
Hi,
me and @anthrotype are working on enabling brace and bracket layers in fontmake and underlying libraries. We are using WorkSans.glyphs to test some bug guards that you might want to know about:

```
Glyph(s) ['Ydieresis.titl', 'a', 'adieresis.titl.sc', 'odieresis.titl.sc', 'udieresis.titl.sc', 'ydieresis.titl.sc'], brace layer '{137,0,-1}' defines more locations than there are design axes.
Glyph(s) ['a'], brace layer '{170, 0,-1}' defines more locations than there are design axes.
Glyph(s) ['ae', 'e'], brace layer '{137,0}' defines more locations than there are design axes.
Glyph(s) ['ae'], brace layer '{170, 0}' defines more locations than there are design axes.
Glyph(s) ['s'], brace layer 'Regular {137,0}' defines more locations than there are design axes.
Glyph(s) ['aogonek_j'], brace layer 'Regular {137, 5}' defines more locations than there are design axes.
Glyph(s) ['aogonek_j'], brace layer '{170,0,-1}' defines more locations than there are design axes.
DesignSpace sources contain duplicate locations; varLib expects each master to define a unique location. Make sure that you used consistent 'brace layer' names in all the glyph layers that share the same location.
  ['{137,0,-1}', '{137,0}', 'Regular {137,0}', 'Regular {137, 5}'] => {'weight': 137}
  ['{170, 0,-1}', '{170, 0}', '{170,0,-1}'] => {'weight': 170}
```

Basically, there's just one axis but the brace layer names define more locations and some have inconsistent names, leading to duplicates. Glyphs.app doesn't care, but we have taken the stance that this is a user error (handling it like Glyphs would take more code and who wants that?). Trying to build the file into a VF with fontmake will therefore fail with a cryptic error message.

Basically, please rename all brace layers to "... {137}" and "... {170}". Take note about what comes before the braces, so I suggest you e.g. name all the "137" layers "Regular {137}" or just "{137}".

**Comment by anthrotype** [comment]
The reason we implemented it like that was not because we were feeling lazy, but to ensure that the generated designspace file could be rountripped back to .glyphs while keeping he original (inconsistent) brace layer names. We could do it differently (merge brace layers with same location) but then it won’t round trip back the same (which may be ok and better than failing on compile?)

**Comment by weiweihuanghuang** [comment]
Oh thank you, I had the layers named so since I had a bunch of other masters in the same file. I'll rename the layers.

**Comment by weiweihuanghuang** [comment]
Fixed

**Comment by madig** [comment]
Not quite -- you got layer names like `{170,}`, which the code doesn't like. Please remove the comma. Also, there is still `Regular {137}` next to `{137}`. The full layer name is important and there should be just one full layer name associated with one location, so please change _every 137 layer_ to either `{137}` or `Regular {137}` (respectively 170).

**Comment by weiweihuanghuang** [comment]
Thanks for spotting those! Fixed now. That `g_idieresis` is a non exporting glyph, I've fixed the name as well anyway

**Comment by madig** [comment]
Thanks for fixing things up, I can indeed build a VF TTF out of both files now. Is the different OS/2.usWinDescent in WorkSans-Italic intentional (322, 343, 343)?

**Comment by weiweihuanghuang** [comment]
Ohhh, those values shouldn't be different...
