### ISSUE TITLE
v2.03 fi ligature displaying incorrectly

### ISSUE THREAD

**Issue by nels-anderson** [weiweihuanghuang/Work-Sans#39]
The fi ligature for the current version of the static fonts is displaying incorrectly. The OTF version seems to be working fine so maybe the ttf, woff, woff2 files just need to be updated to the latest version.

The fonts are being rendered via [opentype.js](https://opentype.js.org)

### WorkSans Medium TTF
![worksans-medium_ligatures_ttf](https://user-images.githubusercontent.com/6685703/56375179-72462b00-61ca-11e9-8502-872239128566.PNG)

### WorkSans Medium OTF
![worksans-medium_ligatures_otf](https://user-images.githubusercontent.com/6685703/56375384-fdbfbc00-61ca-11e9-8bf1-ac2bfd75a27f.PNG)

**Comment by weiweihuanghuang** [comment]
Thanks for reporting this, this is unfortunately a Glyphs App issue, waiting on them for this one.

**Comment by weiweihuanghuang** [comment]
Fixed
