### ISSUE TITLE
Error in ctrl files for SemiBold and Bold

### ISSUE THREAD

**Issue by moyogo** [weiweihuanghuang/Work-Sans#4]
ttfautohint 1.3 complains and fails to hint SemiBold and Bold:
```
hinting/WorkSans-SemiBold.ctrl:10:9: invalid range (values must be within [0;42]) (0x208)
  a touch 44 yshift -0.125 @25,26 # top of bot storke
          ^
WorkSans-SemiBold.ttf hinted
hinting/WorkSans-Bold.ctrl:36:22: invalid range (values must be within [0;95]) (0x208)
  g_j.liga touch 85,95,96 yshift -0.5 @21-22
                       ^
WorkSans-Bold.ttf hinted
```

**Comment by weiweihuanghuang** [comment]
That's odd, I'll look into it soon. point 44 exists in the .ttf though?
![screen shot 2015-03-20 at 10 01 44 am](https://cloud.githubusercontent.com/assets/1271897/6748633/21c8a06e-cee8-11e4-926c-3953e520fd82.png)

**Comment by moyogo** [comment]
I'm exporting from Glyphs
1.4.5 with .glyph file.
These TTF outlines I get are different for SemiBold and Bold if I compare with the ones in fonts/webfonts/ttf. So it's not ttfautohint but Glyphs.app.

For example the SemiBold /a has only points 19-20-21 and 37-38-39 in my screenshot below instead of the 19-20-21-22 and 38-39-40-41 in your screenshot.
![capture d ecran 2015-03-20 a 09 54 26](https://cloud.githubusercontent.com/assets/1923747/6749433/1c235ac8-cee8-11e4-8219-b1df5b8a8a41.png)

**Comment by weiweihuanghuang** [comment]
Ah I should add to my sources that it must be exported from [Glyphs 2](http://www.glyphsapp.com/beta), as it's using [brace](http://www.glyphsapp.com/tutorials/additional-masters-for-individual-glyphs-the-brace-trick) and [bracket](http://www.glyphsapp.com/tutorials/alternating-glyph-shapes) layer features which compensates for interpolation inconsistencies.

**Comment by moyogo** [comment]
OK. I assumed it was Glyphs 1. It’s all good then.
