### ISSUE TITLE
Different line height between regular and italic

### ISSUE THREAD

**Issue by tomkeb** [weiweihuanghuang/Work-Sans#40]
The italics (.otf) have different line height compared to the regular (v2.06).

Image (I tried it in LibreOffice & Word).
![italicsheight](https://user-images.githubusercontent.com/10372446/58038058-38e93e00-7b2f-11e9-9996-37447683b3ce.gif)

**Comment by weiweihuanghuang** [comment]
Oh thanks for the report!

**Comment by weiweihuanghuang** [comment]
Problem shouldn't be there anymore. Are you sure you have the old Work Sans uninstalled?

**Comment by tomkeb** [comment]
I might have had the old version; not happening in 2.007 I just downloaded.
