### ISSUE TITLE
case feature forces lining figures

### ISSUE THREAD

**Issue by david-buck** [weiweihuanghuang/Work-Sans#41]
I can't work out why this should happen. Looking at the feature code, it forces .osf to .lf, but forces .tosf to .lf also. 

I would expect that second set of rules to be .tosf > .tf

![image](https://user-images.githubusercontent.com/5119820/60933798-fd414800-a317-11e9-88e6-3c845a899796.png)

**Comment by weiweihuanghuang** [comment]
Thanks for spotting that! @schriftgestalt looks like Glyphs App is automatically doing this, is this a bug?

**Comment by weiweihuanghuang** [comment]
Thank you for pointing that out! I agree it should not be like this. Seems like the Glyphs App default behaviour is wrong @schriftgestalt ?

**Comment by david-buck** [comment]
I feel like I should have noticed that, sorry.

**Comment by weiweihuanghuang** [comment]
I have update the code !

**Comment by schriftgestalt** [comment]
I’ll have a look.

**Comment by schriftgestalt** [comment]
The code tried to substitute everything into `.lf`. Me as a typographer thinks this would be what I want. But I see that others might have different ideas about this.
