### ISSUE TITLE
Google font Work Sans has stopped working in Google Chrome

### ISSUE THREAD

**Issue by oshihirii** [weiweihuanghuang/Work-Sans#42]
If I open [this jsFiddle](https://jsfiddle.net/rwone/v02L1beh) in Chrome Version 77.0.3865.90 (Official Build) (64-bit) it doesn't seem to work, however it works in Firefox Quantum 69.0.1 (64-bit).  

**HTML**
```html
<head>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Roboto+Mono|Work+Sans:400,700&display=swap" rel="stylesheet">
</head>
```

**Comment by oshihirii** [comment]
FYI, removing the `https://` from the link seems to make the Work Sans font work ([jsFiddle](https://jsfiddle.net/rwone/L3osvy9q)) - not sure why though, other fonts were working with the `https://` prefix.

**Comment by J15t98J** [comment]
Working fine in Chrome 78.0.3904.87
