### ISSUE TITLE
Oslash slash rendering issue on Chrome for Windows

### ISSUE THREAD

**Issue by oymo** [weiweihuanghuang/Work-Sans#46]
First of all, thanks for a great font!
We are experiencing an issue rendering the font on Windows (7, 8, 8.1 and 10) using the latest Chrome browser (version 80.0.3987.132)
We are importing Work Sans using:
@charset “UTF-8”;
@import url(“https://fonts.googleapis.com/css?family=Work+Sans:600,700”);

The following screenshots illustrate the problems rendering the ø letter:
<img width="884" alt="Skærmbillede 2020-03-13 kl  08 21 50" src="https://user-images.githubusercontent.com/613290/76602805-feacbb00-650b-11ea-8b84-6caa42d93903.png">
![Øer](https://user-images.githubusercontent.com/613290/76602819-03716f00-650c-11ea-9ef0-c5b32c49da5a.JPG)

Could this be a bug in this repo? Or is it Google Fonts not having updated to include your latest commit https://github.com/weiweihuanghuang/Work-Sans/commit/dcdcfac3782757f5077f1897c2df4e9667021036 ?

**Comment by weiweihuanghuang** [comment]
This is due to the one on Google still being a few commits behind. @m4rc1e ?

**Comment by m4rc1e** [comment]
Just PRing the latest fonts here. Thanks for the quick fix. https://github.com/google/fonts/pull/2393
