### ISSUE TITLE
Tag release for newest version

### ISSUE THREAD

**Issue by rensbaardman** [weiweihuanghuang/Work-Sans#48]
Thanks so much for the beautiful typeface and the addition of italics. Unfortunately, the latest [tagged release](https://github.com/weiweihuanghuang/Work-Sans/releases) is v1.6. This one doesn't include the italics and all other improvements.

Could you tag the most recent release in the same way as before? This also makes it easier to manage new versions in package managers such as [Homebrew Cask Fonts](https://github.com/Homebrew/homebrew-cask-fonts).

**Comment by weiweihuanghuang** [comment]
Thanks for the reminder!
