### ISSUE TITLE
Support for font-variant-numeric: tabular-nums

### ISSUE THREAD

**Issue by frankie-tech** [weiweihuanghuang/Work-Sans#49]
Link to MDN: [🔗](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric)

I ran into an issue using the font inside of a table and it began messing with the width of the different columns. It would be cool if this could be supported in the future! 😁

**Comment by weiweihuanghuang** [comment]
Tabular figures are definitely in the fonts and work in the browser for me, are you having this issue with other fonts too?

**Comment by weiweihuanghuang** [comment]
Oh I realised you must be using the imported fonts from Google Fonts – does GF still not serve opentype features? @davelab6

**Comment by frankie-tech** [comment]
You're right I'm using Google Fonts, it hadn't occurred to me that there might be a discrepancy in the two versions.

**Comment by davelab6** [comment]
Yeah GF API still has no feature support :(
