### ISSUE TITLE
 The capital A looks very strange in all browsers (Mac)

### ISSUE THREAD

**Issue by jan-scorl** [weiweihuanghuang/Work-Sans#51]
<img width="340" alt="Screenshot 2020-07-11 at 00 57 06" src="https://user-images.githubusercontent.com/17554280/87209328-bebae080-c311-11ea-8f33-22bcd6479e1e.png">

**Comment by weiweihuanghuang** [comment]
Issue is being addressed here already https://github.com/weiweihuanghuang/Work-Sans/issues/47
