### ISSUE TITLE
Font 'may not embed' in Microsoft publisher

### ISSUE THREAD

**Issue by fjclarkson** [weiweihuanghuang/Work-Sans#52]

**Comment by weiweihuanghuang** [comment]
I don't know if Google fonts are specc'd to support this? @davelab6

**Comment by fjclarkson** [comment]
Yeah I’m not sure either. Seems to work fine with work sans in word though. Cheers for the speedy reply

**Comment by davelab6** [comment]
fsType should be 0, that is what I immediately think of
