### ISSUE TITLE
Issue with letter i appearing as a capital when it is the first letter in a Word

### ISSUE THREAD

**Issue by RosZLee** [weiweihuanghuang/Work-Sans#55]
This is happening in Word documents (Office 365 Apps for enterprise)
here's an example of the problem:

Isnt It a Ideal day for building an Igloo

Only workaround is to 1: type the 'i' twice  then 2: delete the capital eg

1.  Iisnt It a Iideal day for building an Iigloo
2.  isnt It a ideal day for building an igloo

**Comment by weiweihuanghuang** [comment]
That's not a problem with the font, I think that's your OS
