### ISSUE TITLE
Other letters with same issue as A

### ISSUE THREAD

**Issue by miinx** [weiweihuanghuang/Work-Sans#57]
Hi there,

Thanks for the `A` fix!  Unfortunately, there are other letters that have the same issue, is it possible to get a fix for them too?

<img width="266" alt="worksans-broken-caps" src="https://user-images.githubusercontent.com/1623076/111589336-d4759380-8818-11eb-97e5-ecb7cd64df38.png">

Thanks for any help you can provide!

**Comment by weiweihuanghuang** [comment]
Where are you using this? If it is a vector app, you need to outline and remove overlaps on the text. Otherwise you should use the fonts provided in this repo insead.

**Comment by miinx** [comment]
Thanks for your fast reply.  This is all done via CSS.  The font colour is transparent, & we're using CSS to outline the font strokes. 

I've put together a demo for you here so you can inspect the font & code:  https://msha.ke/mxtest/

Thanks again!

**Comment by miinx** [comment]
Note the demo is using Work Sans directly from Google Fonts.  The pic I used above used your latest version with the fixed A.

**Comment by weiweihuanghuang** [comment]
I can't make the same adjustments for some of those for interpolation sake. Please self-host the fonts from this repo.

**Comment by miinx** [comment]
Ok, we'll look into doing that, thanks.
