### ISSUE TITLE
VF: issues in STAT table

### ISSUE THREAD

**Issue by thlinard** [weiweihuanghuang/Work-Sans#60]
- Work Sans Italic: "Italic" in `Weight` axis; `namerecord` nameID 260 is "Italic", should be "Regular", with `Flags value="2"` in the STAT table.
- Work Sans: Regular non elidable, Roman non elidable.

Results in Word for Mac (since February 2021 update):
<img width="288" alt="Work Sans" src="https://user-images.githubusercontent.com/13808824/112630218-8cb4c480-8e35-11eb-832d-5ab3495493c8.png">

`gftools gen-stat` could solve the problem.

See google/fonts#3267 and https://github.com/google/fonts/issues/2391

**Comment by weiweihuanghuang** [comment]
Thank you!
