### ISSUE TITLE
The letter "E" in Work Sans pixelates when exported from InDesign to Adobe PDF

### ISSUE THREAD

**Issue by hbouchez** [weiweihuanghuang/Work-Sans#61]
We are using Work Sans in a book for the titles and subtitles and when the designer exports the file from InDesign to a PDF using Adobe Acrobat and prints it—it pixelates. Printing directly from InDesign it acts fine. We've tried saving it all kinds of different ways in Adobe Acrobat and nothing works. I realize Google fonts are meant for primarily for screen but we'd love to be able to use it. Any ideas? Thanks in advance. Helena

![Work Sans Pixelated E](https://user-images.githubusercontent.com/85899691/121943273-6bba8c00-cd1f-11eb-9a51-7a54be3ec954.png)

**Comment by kenmcd** [comment]
That is an issue with the overlaps, not 

> it pixelates

It is an issue with the overlaps, not pixelation.
Are you using the variable font?

**Comment by weiweihuanghuang** [comment]
Please use the static fonts instead of the variable fonts

**Comment by hbouchez** [comment]
Thank you. Will do. 

Helena Bouchez
Executive Words: Business Storytellers & Business Book Shepherds
(609) 851-5166
ExecutiveWords.com
