### ISSUE TITLE
A request for an opentail "g"

### ISSUE THREAD

**Issue by benignant** [weiweihuanghuang/Work-Sans#64]
I really like this font, but the "g" is too different from most default browser/OS fonts. Is there any chance we can get an opentail (single-story) "g"? Perhaps as some kind of option so nothing is changed?

I apologize for not opening a PR. I have no design skills.

**Comment by kenmcd** [comment]
> 
> 
> I really like this font, but the "g" is too different from most default browser/OS fonts. Is there any chance we can get an opentail (single-story) "g"? Perhaps as some kind of option so nothing is changed?
> 
> I apologize for not opening a PR. I have no design skills.

Stylistic Set 01 (ss01) is a simple g.

![simple-g](https://user-images.githubusercontent.com/844920/125707022-1cb948fa-b7a2-4d3d-9f66-6c385d61352e.png)

**Comment by weiweihuanghuang** [comment]
Thanks @kenmcd

**Comment by benignant** [comment]
Thank you @kenmcd! It works perfectly.
