### ISSUE TITLE
Add Greek and Cyrillic

### ISSUE THREAD

**Issue by MarcoMahone** [weiweihuanghuang/Work-Sans#68]
I know this almost seems like a copy of #27 but I want FULL Greek. Please do it for the font files and not just the source files. Also add Bulgarian to this font as well.

**Comment by MarcoMahone** [comment]
I'm gonna use this font for a project that has the word exploration in Russia. If I use this font for a website and people that use either Greek and Cyrillic translate it to their language of Greek and Cyrillic, this font won't show up. So please add Greek, Cyrillic and Bulgarian Localization otherwise I can't use it when it comes to those letters.

**Comment by MarcoMahone** [comment]
Hello? Is Wei here?!

**Comment by weiweihuanghuang** [comment]
I take pull requests

**Comment by MarcoMahone** [comment]
Sorry. I don't know how to do it. But seriously can you add Greek, Cyrillic and Bulgarian Localization

**Comment by kenmcd** [comment]
> 
> 
> Sorry. I don't know how to do that. But seriously can you add Greek, Cyrillic and Bulgarian Localization?

Just a curiosity question ... 
How long do you think it would take a knowledgeable font designer to do all this?

**Comment by MarcoMahone** [comment]
I don't know... A week??

**Comment by MarcoMahone** [comment]
Actually... Wei, do you think you SHOULD do this?

**Comment by kenmcd** [comment]
> I don't know... A week??

Wow, just a week.
I thought it would take much longer.
But it is probably at most a couple hundred glyphs for each master.
And there are only six masters.
It would also be nice to have small caps.
So somewhere between 1,000 - 2,000 glyphs.
Not a big deal.
Drawing, spacing, harmonizing the shapes, adding anchors and marks, matching the color, kerning, OpenType features, hinting, testing - maybe add a day or two for these.
A week - yeah I can see it.
Piece of cake.
So, Wei, please just put your life on hold for "a week" and get this done!

[insert howling laughter here]

**Comment by MarcoMahone** [comment]
Oh so a month?

**Comment by hpapazian** [comment]
> How long do you think it would take a knowledgeable font designer to do all this?

Good question... but moot when the motivation is absent.

**Comment by weiweihuanghuang** [comment]
> Sorry. I don't know how to do that. But seriously can you add Greek, Cyrillic and Bulgarian Localization?

You're free to learn or pay for it.

A rough estimate for making full Greek and Cyrillic for Work Sans (6 font masters) would be 3–4 months. 

> Good question... but moot when the motivation is absent.

Too bad my landlord doesn't accept motivation as rent either.

**Comment by hpapazian** [comment]
Just start with part of it, at whatever pace balances paying bills with the duty towards typographic diversity.
https://en.wikipedia.org/wiki/Noblesse_oblige

**Comment by patrulea** [comment]
wei please pay my bills

**Comment by MatthewCarter420** [comment]
> So are you gonna do this?

I heard Ligma forked this to work on it already.

**Comment by weiweihuanghuang** [comment]
> Just start with part of it, at whatever pace balances paying bills with the duty towards typographic diversity. https://en.wikipedia.org/wiki/Noblesse_oblige

I look forward to your contributions!

**Comment by hpapazian** [comment]
> I look forward to your contributions!

Since 1983.

**Comment by alexburba** [comment]
> I'm gonna use this font for a project that has the word exploration in Russia. If I use this font for a website and people that use either Greek and Cyrillic translate it to their language of Greek and Cyrillic, this font won't show up. So please add Greek, Cyrillic and Bulgarian Localization otherwise I can't use it when it comes to those letters.

I have created Cyrillic version for Regular and Bold styles, but no Greek or Bulgarian.
https://github.com/alexburba/Work-Sans-Cyr-Typeface

**Comment by hpapazian** [comment]
> > I'm gonna use this font for a project that has the word exploration in Russia. If I use this font for a website and people that use either Greek and Cyrillic translate it to their language of Greek and Cyrillic, this font won't show up. So please add Greek, Cyrillic and Bulgarian Localization otherwise I can't use it when it comes to those letters.
> 
> I have created Cyrillic version for Regular and Bold styles, but no Greek or Bulgarian. https://github.com/alexburba/Work-Sans-Cyr-Typeface

Bravo!
