### ISSUE TITLE
Naming of ExtraBold (WOFF2)

### ISSUE THREAD

**Issue by JoshApos** [weiweihuanghuang/Work-Sans#7]
The filename for the ExtraBold weight in the WOFF2 format is written as 'Extrabold', as opposed to 'ExtraBold' as it is elsewhere. Leaves open the chance for someone to reference the improper filename in code.

(Ps. Thanks for making this great typeface!)

**Comment by weiweihuanghuang** [comment]
woops thanks for catching this!
