### ISSUE TITLE
ss01 doesn't work from TypeKit

### ISSUE THREAD

**Issue by jimlears** [weiweihuanghuang/Work-Sans#73]
I can't seem to get `ss01` (alternate a) to work from TypeKit.

Using identical CSS `font-feature-settings: "ss01", "ss06";` the top H1 is served from TypeKit, the bottom H1 is a self hosted woff2.  

`ss06` (alternate g) is working fine in both cases, so it _appears_ TypeKit supports these OpenType features to some degree.

![Screen Shot 2022-04-15 at 11 23 01 AM](https://user-images.githubusercontent.com/561488/163601768-b53e582b-7255-432d-9d47-e282f72ac655.png)

Any clues?

**Comment by weiweihuanghuang** [comment]
Typekit probably doesn't have the latest files. I don't have control over Typekit.

**Comment by jimlears** [comment]
@weiweihuanghuang Understood, I'll reach out to TypeKit
