### ISSUE TITLE
Numbers alignment

### ISSUE THREAD

**Issue by michalis-h** [weiweihuanghuang/Work-Sans#78]
This is a very pretty font! 

There's one drawback however that means I cannot use it and that is that the numbers are not monospaced. E.g. $1,111.00 will not be vertically aligned with $6,000.00, which is kind of necessary for either invoices or scientific/finance presentations.

Is this something that can be addressed? 

Amazing work nonetheless!

**Comment by weiweihuanghuang** [comment]
Yes, use the tabular lining numebrs feature. Activate it either in the OpenType part of your app or if you're on the web using the `tnum` css feature:

https://helpx.adobe.com/fonts/using/open-type-syntax.html#tnum

If your app doesn't support it then I can't help you.

**Comment by michalis-h** [comment]
Unfortunately, this does not address my needs which are more related to Microsoft Suite and Google Drive documents. 

Thanks for responding anyway Wei!

**Comment by weiweihuanghuang** [comment]
Depending on your Microsoft Office Suite, you may have the option to activate "Tabular" spacing:

https://darrengoossens.wordpress.com/2021/03/18/old-style-vs-lining-tabulating-figures-in-word/

As for Google Docs, that's up to Google to support.
