### ISSUE TITLE
j with a too small dot

### ISSUE THREAD

**Issue by blynx** [weiweihuanghuang/Work-Sans#9]
Hi,

You probably already know, but I might just throw in here the too small dot in the j in some weights:

![screen shot 2015-06-22 at 15 00 26](https://cloud.githubusercontent.com/assets/10874163/8282241/6fe63ea4-18ef-11e5-8f37-bf51186d7495.png)

**Comment by weiweihuanghuang** [comment]
Thanks for reporting it! I had no idea — an interpolation issue.

**Comment by weiweihuanghuang** [comment]
Fixed!
